name: Rulesetes protection

on:
  workflow_dispatch:

jobs:
  Rulesetes-Protection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - id: read-json-rules
        run: echo "RULESETS=$(jq -c . < ./ruleset_main_develop.json)" >> $GITHUB_OUTPUT
      

      - name: Set protection rules on selected repositories
        run: |
          repo_names=$(jq -r '.repositories[].repo_name' repositories.json) && echo $repo_names
          owner=$(jq -r '.owner' repositories.json) && echo $owner
          count=0
          
          for u in $repo_names
          do
          count=$((count + 1))
          echo " "
          echo "injection nro $count"
          echo "creando rulesets en repositorio $u"

          project_names=$(echo "$u" | sed 's/-.*//')
          
          echo "ruleset main and develop"
          
          curl -s -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$owner/$u/rulesets \
          -d '${{ steps.read-json-rules.outputs.RULESETS }}' | jq -r '._links.html.href'

          TEAM_ID=$(curl -s -X GET \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          "https://api.github.com/orgs/BancoBice/teams/bitbucket-$project_names-tl" | jq -r '.id')
          echo "team id $TEAM_ID"
          echo "ruleset release"
          if [ "$TEAM_ID" = "null" ]; then
              echo "TEAM_ID es igual a 'null'"
                  curl -s -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  "https://api.github.com/repos/$owner/$u/rulesets" \
                  -d '{
                      "name": "Release Ruleset to BICE Org",
                      "target": "branch",
                      "source_type": "Organization",
                      "enforcement": "active",
                      "conditions": {
                          "ref_name": {
                              "include": [
                                  "refs/heads/release"
                              ],
                              "exclude": []
                          }
                      },
                      "bypass_actors": [
                          {
                              "actor_id": 8853596,
                              "actor_type": "Team",
                              "bypass_mode": "always"
                          }
                      ],
                      "rules": [
                          {
                              "type": "commit_message_pattern",
                              "parameters": {
                                  "operator": "starts_with",
                                  "pattern": "AB#"
                              }
                          },
                          {
                              "type": "pull_request",
                              "parameters": {
                                  "require_code_owner_review": true,
                                  "require_last_push_approval": true,
                                  "dismiss_stale_reviews_on_push": false,
                                  "required_approving_review_count": 1,
                                  "required_review_thread_resolution": false
                              }
                          },
                          {
                              "type": "non_fast_forward"
                          },
                          {
                              "type": "creation",
                              "parameters": {}
                          },
                          {
                              "type": "update",
                              "parameters": {
                                  "update_allows_fetch_and_merge": true
                              }
                          },
                          {
                              "type": "required_signatures",
                              "parameters": {}
                          }
                      ]
                  }' | jq -r '._links.html.href'
          else
              echo "TEAM_ID no es igual a 'null'"
              curl -s -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$owner/$u/rulesets \
              -d '{
                  "name": "Release Ruleset to BICE Org",
                  "target": "branch",
                  "source_type": "Organization",
                  "enforcement": "active",
                  "conditions": {
                      "ref_name": {
                          "include": [
                              "refs/heads/release"
                          ],
                          "exclude": []
                      }
                  },
                  "bypass_actors": [
                      {
                          "actor_id": 8853596,
                          "actor_type": "Team",
                          "bypass_mode": "always"
                      },
                      {
                          "actor_id": '"$TEAM_ID"',
                          "actor_type": "Team",
                          "bypass_mode": "always"
                      }
                  ],
                  "rules": [
                      {
                          "type": "commit_message_pattern",
                          "parameters": {
                              "operator": "starts_with",
                              "pattern": "AB#"
                          }
                      },
                      {
                          "type": "pull_request",
                          "parameters": {
                              "require_code_owner_review": true,
                              "require_last_push_approval": true,
                              "dismiss_stale_reviews_on_push": false,
                              "required_approving_review_count": 1,
                              "required_review_thread_resolution": false
                          }
                      },
                      {
                          "type": "non_fast_forward"
                      },
                      {
                          "type": "creation",
                          "parameters": {}
                      },
                      {
                          "type": "update",
                          "parameters": {
                              "update_allows_fetch_and_merge": true
                          }
                      },
                      {
                          "type": "required_signatures",
                          "parameters": {}
                      }
                  ]
              }' | jq -r '._links.html.href'
          fi

          echo "ruleset feacture"

          curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$owner/$u/rulesets \
            -d '{
              "name": "Feature Ruleset to BICE Org",
              "target": "branch",
              "source_type": "Organization",
              "enforcement": "active",
              "conditions": {
                  "ref_name": {
                      "include": [
                          "refs/heads/feature",
                          "refs/heads/feature/*"
                      ],
                      "exclude": []
                  }
              },
              "rules": [
                  {
                      "type": "commit_message_pattern",
                      "parameters": {
                          "operator": "starts_with",
                          "pattern": "AB#"
                      }
                  }
              ]
          }' | jq -r '._links.html.href'
          done





          

